### ISSUE TITLE
Add 1 ingredient to recipe

### ISSUE THREAD

**Issue by sgtnasty** [nnasa14/recipes#1]
Without having to re-enter the entire recipe list, add a method which takes 1 or more arguments of strings and ADDs them to the recipe without removing the original ingredients.

Also if the ingredient already exists, then warn user and do nothing.

**Comment by sgtnasty** [comment]
Does commit 9f0c2b6 solve this issue?

**Comment by nnasa14** [comment]
Roger. Closing this issue with 9f0c2b5
