### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by sgtnasty** [nnasa14/recipes#10]
Need to save settings in a config file, perhaps JSON (its built into python)

1. https://docs.python.org/3/library/json.html
2. https://docs.python.org/3/library/configparser.html
3. https://docs.python.org/3/library/tomllib.html

**Comment by sgtnasty** [comment]
Save the location of the recipes database for example

**Comment by nnasa14** [comment]
Would it be best to use the configparser module to solve this issue?

**Comment by sgtnasty** [comment]
yes, that lib for python is built in, and does INI files.

**Comment by sgtnasty** [comment]
See this for https://en.wikipedia.org/wiki/INI_file

**Comment by nnasa14** [comment]
Added config to main.py in commit cbebaa7559b4267b1271af8b047f97fd08bb10ff
