### ISSUE TITLE
Implement Python class members (built-in class functions)

### ISSUE THREAD

**Issue by sgtnasty** [nnasa14/recipes#3]
Implement __new__, __init__ etc. for the Recipes class. See: 

1. https://docs.python.org/3/reference/datamodel.html?highlight=__str__#special-method-names
2. https://www.bogotobogo.com/python/python_classes_instances.php

Implement:
* __init__
* __str__
* __repr__

**Comment by nnasa14** [comment]
Edited init in Recipe and Ingredients class, added str function to Recipes class in commit 2bdaa5f2ece36a9218633d8c176d1096ebd3be54

**Comment by nnasa14** [comment]
Last item to add for both classes is __repr__ funct

**Comment by nnasa14** [comment]
Added repr function in both classes with commit 3ab4194484528a69a0503e0c5f27f5214873a1f7
