### ISSUE TITLE
Move ingredients list into its own class with its own methods to CRUD

### ISSUE THREAD

**Issue by sgtnasty** [nnasa14/recipes#4]
Ingredients should be a separate class with methods not just a list.

**Comment by sgtnasty** [comment]
CRUD - https://en.wikipedia.org/wiki/Create,_read,_update_and_delete

**Comment by nnasa14** [comment]
Closing with commits 9027f79d73a63140dc2c76b58320a34812f405a3 and 34d2012f74baf08082f0cc231258381548e1ffcd

**Comment by nnasa14** [comment]
Need to fix ingredients class replicating existing recipes, need to add str function.

**Comment by nnasa14** [comment]
Added str function with commit bfc83755e860d97506ca554746bdec2f75e3dae5 

Last item to add to close issue is __repr__ function

**Comment by nnasa14** [comment]
Added repr function with commit 3ab4194484528a69a0503e0c5f27f5214873a1f7
