### ISSUE TITLE
Code needs documentation

### ISSUE THREAD

**Issue by sgtnasty** [nnasa14/recipes#7]
The source code looks great but needs proper python docs.

1. https://docs.python.org/
1. https://docs.python-guide.org/writing/documentation/
1. https://realpython.com/documenting-python-code/#documenting-your-python-code-base-using-docstrings

**Comment by nnasa14** [comment]
Added docstrings for classes Recipes and Ingredients in commit 698a8a507a962f096e4c9c4a65df2812acf0942a

When adding docstrings to classes, it is necessary to add them for the functions within them?

**Comment by sgtnasty** [comment]
Yes, those functions tend to do most of the work, therefor need more docs to explain.

**Comment by nnasa14** [comment]
Added docstrings to the functions in Recipes and Ingredients classes b6c9e8a3d230ded65a833b84d9dab0c62e0b9146
